server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wiztip?useSSL=false&serverTimezone=UTC
    username: root
    password: 1qaz@WSX
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

quartz:
  job-store-type: memory
  properties:
    org.quartz.scheduler.instanceName: WiztipScheduler
    org.quartz.threadPool.threadCount: 5

# Aliyun / LLM placeholders - replace with real keys in production
wiztip:
  aliyun:
    oss:
      endpoint: "oss-cn-shanghai.aliyuncs.com"
      bucket: "your-bucket-name"
      accessKeyId: "YOUR_ACCESS_KEY_ID"
      accessKeySecret: "YOUR_ACCESS_KEY_SECRET"
  asr:
    appKey: "YOUR_ASR_APP_KEY"
    accessKeyId: "YOUR_ACCESS_KEY_ID"
    accessKeySecret: "YOUR_ACCESS_KEY_SECRET"
  llm:
    apiKey: "YOUR_QWEN_API_KEY"
    endpoint: "https://dashscope.aliyuncs.com/api/v1/services/your-service-id/gen" 
